version: '3'
services:
    tf:
        build: ./
        image: tf-learning
        ports:
            - 6006:6006
        volumes:
            - ./:/learning
        command: bash -c "while [ 1 ]; do sleep 1; done"
