version: '3'
services:
    tf:
        build: ./
        image: tf-learning
        ports:
            - 6006:6006
        volumes:
            - ./:/learning
            - ./.vimrc:/root/.vimrc
            - ./.vim:/root/.vim
        env_file:
            - ./.env
        command: /learning/enter-point.sh
